// Menu data structure
export const MENU_DATA = [
  {
    "EmblemedId": "",
    "menuCd": " EP01",
    "menuGroup": "E000",
    "moduleCd": "Equipment",
    "menuNm": "Part Management",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "",
    "menuType": "EP01ME001",
    "sortOrder": 6
  },
  {
    "EmblemedId": null,
    "menuCd": "B000",
    "menuGroup": "",
    "moduleCd": "MasterData",
    "menuNm": "Master",
    "signature": null,
    "menuIcon": "storage",
    "menuParams": "",
    "menuUrl": "",
    "menuType": "MDME0001",
    "sortOrder": 2
  },
  {
    "EmblemedId": null,
    "menuCd": "B001",
    "menuGroup": "C000",
    "moduleCd": "System",
    "menuNm": "Common",
    "signature": 100,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/master-data/common",
    "menuType": "MDCMME0001",
    "sortOrder": 1
  },
  {
    "EmblemedId": null,
    "menuCd": "B003",
    "menuGroup": "B000",
    "moduleCd": "MasterData",
    "menuNm": "Plant",
    "signature": 102,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/master-data/plant-master",
    "menuType": "M002ME0001",
    "sortOrder": 6
  },
  {
    "EmblemedId": null,
    "menuCd": "B004",
    "menuGroup": "B000",
    "moduleCd": "MasterData",
    "menuNm": "Line",
    "signature": 103,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/master-data/work-center",
    "menuType": "M003ME0001",
    "sortOrder": 5
  },
  {
    "EmblemedId": null,
    "menuCd": "B005",
    "menuGroup": "B000",
    "moduleCd": "MasterData",
    "menuNm": "Process",
    "signature": 104,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/master-data/process",
    "menuType": "M004ME0001",
    "sortOrder": 6
  },
  {
    "EmblemedId": null,
    "menuCd": "B006",
    "menuGroup": "B000",
    "moduleCd": "MasterData",
    "menuNm": "Routing",
    "signature": 105,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/master-data/routing",
    "menuType": "M005ME0001",
    "sortOrder": 7
  },
  {
    "EmblemedId": null,
    "menuCd": "B008",
    "menuGroup": "B000",
    "moduleCd": "MasterData",
    "menuNm": "Department",
    "signature": 194,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/master-data/department",
    "menuType": "M008ME0001",
    "sortOrder": 9
  },
  {
    "EmblemedId": null,
    "menuCd": "B009",
    "menuGroup": "B000",
    "moduleCd": "MasterData",
    "menuNm": "Item",
    "signature": 191,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/master-data/item-master",
    "menuType": "M001ME0001",
    "sortOrder": 1
  },
  {
    "EmblemedId": null,
    "menuCd": "B010",
    "menuGroup": "B000",
    "moduleCd": "MasterData",
    "menuNm": "Customer",
    "signature": 193,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/master-data/business-partner",
    "menuType": "M010ME0001",
    "sortOrder": 15
  },
  {
    "EmblemedId": null,
    "menuCd": "B011",
    "menuGroup": "B000",
    "moduleCd": "MasterData",
    "menuNm": "BOM",
    "signature": 189,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/master-data/bom",
    "menuType": "M009ME0001",
    "sortOrder": 2
  },
  {
    "EmblemedId": "",
    "menuCd": "B012",
    "menuGroup": "B000",
    "moduleCd": "MasterData",
    "menuNm": "Item Group",
    "signature": 190,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master-data/item-group",
    "menuType": "B012ME0001",
    "sortOrder": 10
  },
  {
    "EmblemedId": "",
    "menuCd": "B013",
    "menuGroup": "B000",
    "moduleCd": "MasterData",
    "menuNm": "Item Class",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master-data/item-class",
    "menuType": "B013ME0001",
    "sortOrder": 11
  },
  {
    "EmblemedId": "",
    "menuCd": "B015",
    "menuGroup": "P000",
    "moduleCd": "MasterData",
    "menuNm": "Cut BOM",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master-data/cut-bom",
    "menuType": "B015ME0001",
    "sortOrder": 1
  },
  {
    "EmblemedId": "",
    "menuCd": "B016",
    "menuGroup": "V000",
    "moduleCd": "MasterData",
    "menuNm": "Removal Strategy",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master-data/removal-strategy",
    "menuType": "B016ME0001",
    "sortOrder": 20
  },
  {
    "EmblemedId": "",
    "menuCd": "B017",
    "menuGroup": "Q000",
    "moduleCd": "MasterData",
    "menuNm": "Sampling Inspection Master",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master-data/sampling-inspection-master",
    "menuType": "B017ME0001",
    "sortOrder": 1
  },
  {
    "EmblemedId": null,
    "menuCd": "C000",
    "menuGroup": "",
    "moduleCd": "System",
    "menuNm": "System",
    "signature": null,
    "menuIcon": "settings",
    "menuParams": "",
    "menuUrl": "",
    "menuType": "SYME0001",
    "sortOrder": 8
  },
  {
    "EmblemedId": null,
    "menuCd": "C003",
    "menuGroup": "C000",
    "moduleCd": "System",
    "menuNm": "User Group",
    "signature": null,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/system/user-group-management",
    "menuType": "SYUSME0001",
    "sortOrder": 4
  },
  {
    "EmblemedId": null,
    "menuCd": "C004",
    "menuGroup": "C000",
    "moduleCd": "System",
    "menuNm": "Program",
    "signature": null,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/system/program-master",
    "menuType": "C004ME0001",
    "sortOrder": 3
  },
  {
    "EmblemedId": null,
    "menuCd": "C006",
    "menuGroup": "C000",
    "moduleCd": "System",
    "menuNm": "User Group Authorize",
    "signature": null,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/system/group-authorization",
    "menuType": "SYGAME0001",
    "sortOrder": 5
  },
  {
    "EmblemedId": null,
    "menuCd": "C007",
    "menuGroup": "C000",
    "moduleCd": "System",
    "menuNm": "Language",
    "signature": 187,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/system/languages",
    "menuType": "SYLMME0001",
    "sortOrder": 2
  },
  {
    "EmblemedId": "",
    "menuCd": "C008",
    "menuGroup": "B000",
    "moduleCd": "System",
    "menuNm": "Employee",
    "signature": 188,
    "menuIcon": "",
    "menuParams": "/system/employee",
    "menuUrl": "/system/employee",
    "menuType": "M007ME0001",
    "sortOrder": 10
  },
  {
    "EmblemedId": "",
    "menuCd": "D000",
    "menuGroup": null,
    "moduleCd": "Sale",
    "menuNm": "Delivery",
    "signature": null,
    "menuIcon": "mdi-truck-delivery-outline",
    "menuParams": null,
    "menuUrl": "",
    "menuType": "D000ME000",
    "sortOrder": 5
  },
  {
    "EmblemedId": null,
    "menuCd": "DB00",
    "menuGroup": "",
    "moduleCd": "Dashboard",
    "menuNm": "Dashboard",
    "signature": null,
    "menuIcon": "analytics",
    "menuParams": "",
    "menuUrl": "",
    "menuType": "DB00ME0000",
    "sortOrder": 1
  },
  {
    "EmblemedId": null,
    "menuCd": "DB01",
    "menuGroup": "DB00",
    "moduleCd": "Dashboard",
    "menuNm": "Dashboard",
    "signature": null,
    "menuIcon": "",
    "menuParams": "",
    "menuUrl": "/dashboard",
    "menuType": "DB00ME0001",
    "sortOrder": 1
  },
  {
    "EmblemedId": "",
    "menuCd": "E000",
    "menuGroup": null,
    "moduleCd": "Equipment",
    "menuNm": "Equipment",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "",
    "menuType": "E000ME0001",
    "sortOrder": 7
  },
  {
    "EmblemedId": "",
    "menuCd": "E001",
    "menuGroup": " EP01",
    "moduleCd": "Equipment",
    "menuNm": "Equipment Regis/Confirm Inbound",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master/equipment-inbound",
    "menuType": "E0001ME0001",
    "sortOrder": 2
  },
  {
    "EmblemedId": "",
    "menuCd": "E003",
    "menuGroup": "E000",
    "moduleCd": "Equipment",
    "menuNm": "Equipment Maintenance",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master/equiment-maintenance",
    "menuType": "E003ME0001",
    "sortOrder": 4
  },
  {
    "EmblemedId": "",
    "menuCd": "E004",
    "menuGroup": "E000",
    "moduleCd": "Equipment",
    "menuNm": "Maintenance Schedule",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master/equipment-schedule",
    "menuType": "E004ME0001",
    "sortOrder": 5
  },
  {
    "EmblemedId": "",
    "menuCd": "E005",
    "menuGroup": "E000",
    "moduleCd": "Equipment",
    "menuNm": "EquimentGroup",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master/equiment-group",
    "menuType": "E005ME0001",
    "sortOrder": 1
  },
  {
    "EmblemedId": "",
    "menuCd": "E006",
    "menuGroup": "E000",
    "moduleCd": "Equipment",
    "menuNm": "EquimentClass",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master/equiment-class",
    "menuType": "E006ME0001",
    "sortOrder": 2
  },
  {
    "EmblemedId": "",
    "menuCd": "E007",
    "menuGroup": "E000",
    "moduleCd": "Equipment",
    "menuNm": "Equipment Master",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master/machine",
    "menuType": "E007ME0001",
    "sortOrder": 3
  },
  {
    "EmblemedId": "",
    "menuCd": "E008",
    "menuGroup": " EP01",
    "moduleCd": "Equipment",
    "menuNm": "Part Master",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master/part-master",
    "menuType": "E008ME0001",
    "sortOrder": 1
  },
  {
    "EmblemedId": "",
    "menuCd": "E009",
    "menuGroup": " EP01",
    "moduleCd": "Equipment",
    "menuNm": "Issue Part",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master/issue-master",
    "menuType": "E009ME0001",
    "sortOrder": 1
  },
  {
    "EmblemedId": "",
    "menuCd": "E010",
    "menuGroup": " EP01",
    "moduleCd": "Equipment",
    "menuNm": "Part Stock",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "/master/equiment-part-stock",
    "menuType": "E010ME0001",
    "sortOrder": 1
  },
  {
    "EmblemedId": "",
    "menuCd": "M000",
    "menuGroup": null,
    "moduleCd": "System",
    "menuNm": "Manual",
    "signature": null,
    "menuIcon": "mdi-book-account-outline",
    "menuParams": null,
    "menuUrl": "",
    "menuType": "M000ME0000",
    "sortOrder": 9
  },
  {
    "EmblemedId": "",
    "menuCd": "M001",
    "menuGroup": "M000",
    "moduleCd": "System",
    "menuNm": "Korean",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "",
    "menuType": "M001ME0023",
    "sortOrder": 1
  },
  {
    "EmblemedId": "",
    "menuCd": "M002",
    "menuGroup": "M000",
    "moduleCd": "System",
    "menuNm": "Vietnamese",
    "signature": null,
    "menuIcon": "",
    "menuParams": null,
    "menuUrl": "",
    "menuType": "M002ME0017",
    "sortOrder": 1
  },
  {
    "EmblemedId": null,
    "menuCd": "P000",
    "menuGroup": "",
    "moduleCd": "Production",
    "menuNm": "Production",
    "signature": null,
    "menuIcon": "precision_manufacturing",
    "menuParams": "",
    "menuUrl": "",
    "menuType": "PD00ME0000",
    "sortOrder": 4
  },
  {
    "EmblemedId": null,
    "menuCd": "Q000",
    "menuGroup": "",
    "moduleCd": "QC",
    "menuNm": "QC",
    "signature": null,
    "menuIcon": "mdi-check",
    "menuParams": null,
    "menuUrl": "",
    "menuType": "Q000ME0000",
    "sortOrder": 6
  },
  {
    "EmblemedId": null,
    "menuCd": "V000",
    "menuGroup": "",
    "moduleCd": "Inventory",
    "menuNm": "Inventory",
    "signature": null,
    "menuIcon": "store",
    "menuParams": "",
    "menuUrl": "",
    "menuType": "IVME0001",
    "sortOrder": 3
  }
];

export default MENU_DATA;
